// Generated from https://models.dev/api.json. Refresh: pnpm providers:catalog
// Snapshot: 2026-10-02. Use top-level keys, not embedded provider IDs.
export const languageModelProviders = {
  '302ai': '302.AI',
  abacus: 'Abacus',
  'abliteration-ai': 'abliteration.ai',
  above: 'above.dev',
  agentrouter: 'AgentRouter',
  agnes: 'Agnes AI',
  'ai-router': 'AI-ROUTER',
  ai21: 'AI21 Labs',
  aiand: 'ai&',
  aihubmix: 'AIHubMix',
  ainetcafe: 'ainetcafe',
  aixy: 'Aixy',
  'aki-io': 'AKI.IO',
  alibaba: 'Alibaba',
  'alibaba-cn': 'Alibaba (China)',
  'alibaba-coding-plan': 'Alibaba Coding Plan',
  'alibaba-coding-plan-cn': 'Alibaba Coding Plan (China)',
  'alibaba-token-plan': 'Alibaba Token Plan',
  'alibaba-token-plan-cn': 'Alibaba Token Plan (China)',
  'amazon-bedrock': 'Amazon Bedrock',
  ambient: 'Ambient',
  amd: 'AMD',
  anthropic: 'Anthropic',
  anyapi: 'AnyAPI',
  arcee: 'Arcee',
  'atomic-chat': 'Atomic Chat',
  auriko: 'Auriko',
  azure: 'Azure',
  'azure-cognitive-services': 'Azure Cognitive Services',
  bailing: 'Bailing',
  baseten: 'Baseten',
  bee: 'Bee by HEOSSI',
  berget: 'Berget.AI',
  blueclaw: 'Blue Claw',
  bothub: 'Bothub',
  cerebras: 'Cerebras',
  chutes: 'Chutes',
  clarifai: 'Clarifai',
  claudinio: 'Claudinio',
  'cline-pass': 'ClinePass',
  'cloudferro-sherlock': 'CloudFerro Sherlock',
  'cloudflare-ai-gateway': 'Cloudflare AI Gateway',
  'cloudflare-workers-ai': 'Cloudflare Workers AI',
  cohere: 'Cohere',
  coralbricks: 'CoralBricks',
  cortecs: 'Cortecs',
  crof: 'CrofAI',
  crossmodel: 'CrossModel',
  crusoe: 'Crusoe',
  daoxe: 'DaoXE',
  databricks: 'Databricks',
  deepinfra: 'Deep Infra',
  deepseek: 'DeepSeek',
  digitalocean: 'DigitalOcean',
  dinference: 'DInference',
  drun: 'D.Run (China)',
  ebcloud: 'EBCloud',
  echo: 'Echo',
  edenai: 'Eden AI',
  empiriolabs: 'EmpirioLabs AI',
  evroc: 'evroc',
  fastrouter: 'FastRouter',
  'fireworks-ai': 'Fireworks AI',
  freemodel: 'FreeModel',
  friendli: 'Friendli',
  frogbot: 'FrogBot',
  'github-copilot': 'GitHub Copilot',
  gitlab: 'GitLab Duo',
  gmicloud: 'GMI Cloud',
  google: 'Google',
  'google-vertex': 'Vertex',
  'google-vertex-anthropic': 'Vertex (Anthropic)',
  greenpt: 'GreenPT',
  groq: 'Groq',
  helicone: 'Helicone',
  hetzner: 'Hetzner',
  'hpc-ai': 'HPC-AI',
  huggingface: 'Hugging Face',
  hyper: 'Charm Hyper',
  iflowcn: 'iFlow',
  impossibl: 'Impossibl',
  inception: 'Inception',
  inceptron: 'Inceptron',
  inco: 'Inco',
  infer: 'Infer by Flow7',
  inference: 'Inference',
  inferx: 'InferX',
  infomaniak: 'Infomaniak',
  'io-net': 'IO.NET',
  iteracompute: 'IteraCompute',
  jalapeno: 'Jalapeno Cloud',
  jiekou: 'Jiekou.AI',
  kenari: 'Kenari',
  kilo: 'Kilo Gateway',
  'kimi-code-plan-cn': 'Kimi For Coding (kimi.com)',
  'kimi-code-plan-global': 'Kimi For Coding (kimi.ai)',
  klokintegration: 'klokintegration.se',
  kosmik: 'Kosmik Compute',
  'kuae-cloud-coding-plan': 'KUAE Cloud Coding Plan',
  lilac: 'Lilac',
  llama: 'Llama',
  llmgateway: 'DevPass (LLM Gateway)',
  'llmgateway-providers': 'LLM Gateway',
  llmtech: 'LLM Tech',
  llmtr: 'LLMTR',
  lmstudio: 'LMStudio',
  longcat: 'LongCat',
  lucidquery: 'LucidQuery',
  lynkr: 'Lynkr',
  meganova: 'Meganova',
  melious: 'Melious',
  'merge-gateway': 'Merge Gateway',
  meta: 'Meta',
  minimax: 'MiniMax (minimax.io)',
  'minimax-cn': 'MiniMax (minimax.cn)',
  'minimax-cn-coding-plan': 'MiniMax Token Plan (minimax.cn)',
  'minimax-coding-plan': 'MiniMax Token Plan (minimax.io)',
  mistral: 'Mistral',
  mixlayer: 'Mixlayer',
  moark: 'Moark',
  modal: 'Modal',
  'model-oracle-ai': 'Model Oracle AI',
  modelis: 'Modelis',
  modelscope: 'ModelScope',
  moonshotai: 'Moonshot AI',
  'moonshotai-cn': 'Moonshot AI (China)',
  morph: 'Morph',
  nan: 'NaN',
  'nano-gpt': 'NanoGPT',
  nearai: 'NEAR AI Cloud',
  nebius: 'Nebius Token Factory',
  neon: 'Neon',
  neosmith: 'NeoSmith',
  neuralwatt: 'Neuralwatt',
  nova: 'Nova',
  'novita-ai': 'NovitaAI',
  nvidia: 'Nvidia',
  oci: 'OCI Generative AI',
  ofox: 'Ofox',
  'ollama-cloud': 'Ollama Cloud',
  openai: 'OpenAI',
  opencode: 'OpenCode Zen',
  'opencode-go': 'OpenCode Go',
  openreason: 'OpenReason',
  openrouter: 'OpenRouter',
  opper: 'Opper',
  orcarouter: 'OrcaRouter',
  ovhcloud: 'OVHcloud AI Endpoints',
  pareto: 'Pareto Inference',
  pendra: 'Pendra',
  perplexity: 'Perplexity',
  'perplexity-agent': 'Perplexity Agent',
  pioneer: 'Pioneer',
  poe: 'Poe',
  poolside: 'Poolside',
  'privatemode-ai': 'Privatemode AI',
  'qihang-ai': 'QiHang',
  'qiniu-ai': 'Qiniu',
  qvac: 'QVAC',
  'regolo-ai': 'Regolo AI',
  requesty: 'Requesty',
  'routing-run': 'routing.run',
  runinfra: 'RunInfra',
  sakana: 'Sakana AI',
  'salad-cloud': 'SaladCloud AI Gateway',
  'sap-ai-core': 'SAP AI Core',
  sarvam: 'Sarvam AI',
  scaleway: 'Scaleway',
  'scnet-token-plan': 'SCNet Token Plan',
  'scx-ai': 'SCX.ai',
  sensenova: 'SenseNova (China)',
  siliconflow: 'SiliconFlow',
  'siliconflow-cn': 'SiliconFlow (China)',
  'snowflake-cortex': 'Snowflake Cortex',
  stackit: 'STACKIT',
  standardcompute: 'Standard Compute',
  stepfun: 'StepFun (China)',
  'stepfun-ai': 'StepFun (Global)',
  'stepfun-ai-step-plan': 'StepFun Step Plan (Global)',
  'stepfun-step-plan': 'StepFun Step Plan (China)',
  subconscious: 'Subconscious',
  submodel: 'submodel',
  synthetic: 'Synthetic',
  tempr: 'Tempr Gateway',
  'tencent-coding-plan': 'Tencent Coding Plan (China)',
  'tencent-token-plan': 'Tencent Token Plan',
  'tencent-tokenhub': 'Tencent TokenHub',
  tensorx: 'TensorX',
  'the-grid-ai': 'The Grid AI',
  thinkingmachines: 'Thinking Machines',
  tinfoil: 'Tinfoil',
  togetherai: 'Together AI',
  tokengo: 'TokenGo',
  tokenrouter: 'TokenRouter',
  trustedrouter: 'TrustedRouter',
  'umans-ai': 'Umans AI',
  'umans-ai-coding-plan': 'Umans AI Coding Plan',
  unorouter: 'UnoRouter',
  upstage: 'Upstage',
  v0: 'v0',
  vancine: 'Vancine',
  venice: 'Venice AI',
  vercel: 'Vercel AI Gateway',
  vispark: 'Vispark',
  vivgrid: 'Vivgrid',
  volcengine: 'Volcengine Ark',
  'volcengine-coding-plan': 'Volcengine Ark Coding Plan',
  vultr: 'Vultr',
  'wafer.ai': 'Wafer',
  wallaby: 'Wallaby',
  wandb: 'CoreWeave',
  watsonx: 'watsonx.ai',
  xai: 'xAI',
  xiaomi: 'Xiaomi',
  'xiaomi-token-plan-ams': 'Xiaomi Token Plan (Europe)',
  'xiaomi-token-plan-cn': 'Xiaomi Token Plan (China)',
  'xiaomi-token-plan-sgp': 'Xiaomi Token Plan (Singapore)',
  xpersona: 'Xpersona',
  zai: 'Z.AI',
  'zai-coding-plan': 'Z.AI Coding Plan',
  zeldoc: 'Zeldoc',
  zenifra: 'Zenifra',
  zenmux: 'ZenMux',
  zhipuai: 'Zhipu AI',
  'zhipuai-coding-plan': 'Zhipu AI Coding Plan',
} as const;
